### ISSUE TITLE
Support internal mirrors of packagecloud repositories

### ISSUE THREAD

**Issue by kscherer** [choria-io/puppet-choria#106]
I like to create internal mirrors of repositories that provide packages used on many machines.

**Comment by ripienaar** [comment]
Thanks a lot @kscherer

**Comment by ExalDraen** [comment]
Hi @kscherer, I'm trying to use this feature that you added and ran into a issue that stumped me: 

* I set up an internal mirror as per the packagcloud docs: first  `reposync` to sync the rpms and then `createrepo` to generate metadata
* I set the `baseurl` to point at my internal repo

Unfortunately, this didn't work because `yum` was unable to find the `repomd.xml.asc` file which I believe has the GPG signatures of the metadata:
```
yum repolist 
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
http://repo.grass.corp/choria/release/el/7/x86_64/repodata/repomd.xml.asc: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
```

I think that's becuase the puppet module (in `repo.pp`) sets `repo_gpgcheck=true` which means yum looks for a repo metadata GPG signature. 

May I ask how you worked around this?

**Comment by kscherer** [comment]
I only tested my patch on Ubuntu, but this problem is not related to this patch. It is an artifact of the differences between apt and yum mirroring. For my rpm mirrors (like CentOS, EPEL, yum.puppetlabs.com), I use rsync  which mirrors the gpg keys and metadata. reposync only transfers packages, not metadata. Interestingly apt-mirror does mirror the full signed metadata. I did some quick research and I think these are your options:

1) Disable gpg_check
2) Sign the mirror with your own gpg key and setup the public key properly
3) Ask packagecloud to enable mirroring rpm repos using rsync or lftp. I tried using lftp but it couldn't get a directory listing.
4) Try mrepo?

Good luck!

**Comment by ripienaar** [comment]
I am ok with the first option if none of the other appeals

**Comment by ExalDraen** [comment]
Hey, thanks for the quick reply. I don't like my odds of (3.) and it's not to clear to me that `mrepo` is different to (2.) since it looks like it just uses `reposync` and `createrepo` under the covers.

Sad to say but we don't have a good setup for GPG signing packages on internal mirrors so I'll have to plumb for 1.

@ripienaar shall I send a PR for making this an option? Or just hard disable `gpg_check`?

**Comment by ripienaar** [comment]
Yeah so the only question is do we make it an option or just remove it. I am not keen on even more options but also think it ads value

Let’s just remove the check on the repo.
