### ISSUE TITLE
packagecloud yum repo appears to have gone away?

### ISSUE THREAD

**Issue by sshipway** [choria-io/puppet-choria#319]
I'm trying to install/upgrade choria on out hosts via puppet, but yum is failing as https://packagecloud.io/choria/release/el/7/x86_64/repodata/repomd.xml is unavailable.  
Has the packagecloud.io repository been closed down?  If so, where should we go to obtain the RPMs now?

**Comment by ripienaar** [comment]
Hello,

Yes as notified in September last year https://choria.io/blog/post/2021/09/22/september_releases/ and again in February https://choria.io/blog/post/2022/02/23/february_releases/ the packagecloud repositories has to be retired due to things out of our control.

You'll have to either use the new repos but ideally upgrade to later choria plugins and versions that will do this automatically for you.
